import { theme } from "./theme";

export const gmStyles = {
  sectionHeaderRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  editingBadge: {
    fontSize: 12,
    padding: "6px 10px",
    borderRadius: 999,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: theme.colors.surface2,
    color: theme.colors.text,
    fontWeight: 800,
    whiteSpace: "nowrap",
  },

  checkboxRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    userSelect: "none",
    marginTop: 8,
  },
  checkboxLabel: {
    color: theme.colors.text,
    fontWeight: 700,
  },

  pickLabel: {
    fontSize: 12,
    color: theme.colors.muted,
    textTransform: "uppercase",
    letterSpacing: 1,
    marginBottom: 8,
    marginTop: 10,
  },
  pillWrap: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
  },
  pill: {
    border: `1px solid ${theme.colors.borderStrong}`,
    background: "#fff",
    color: theme.colors.text,
    padding: "8px 10px",
    borderRadius: 999,
    cursor: "pointer",
    fontWeight: 650,
  },
  pillSelected: {
    background: theme.colors.text,
    color: "#fff",
    border: `1px solid ${theme.colors.borderStrong}`,
  },

  attachButton: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "10px 12px",
    borderRadius: 12,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: theme.colors.surface2,
    color: theme.colors.text,
    cursor: "pointer",
    fontWeight: 800,
  },
  thumbWrap: {
    position: "relative",
    width: 140,
    height: 90,
    borderRadius: 14,
    overflow: "hidden",
    border: `1px solid ${theme.colors.border}`,
    background: "#000",
  },
  thumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  thumbRemove: {
    position: "absolute",
    top: 6,
    right: 6,
    width: 28,
    height: 28,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.35)",
    background: "rgba(0,0,0,0.55)",
    color: "#fff",
    cursor: "pointer",
    fontSize: 18,
    lineHeight: "28px",
    textAlign: "center",
    fontWeight: 900,
  },

  actionRow: {
    display: "flex",
    gap: 10,
    marginTop: 12,
  },
  linkButton: {
    marginTop: 10,
    background: "transparent",
    border: "none",
    padding: 0,
    cursor: "pointer",
    color: "#444",
    textDecoration: "underline",
    fontWeight: 700,
  },

  wrap: {
    minHeight: "100vh",
    display: "grid",
    placeItems: "center",
    padding: theme.spacing.lg,
    background: theme.colors.bg,
  },
  card: {
    width: "min(900px, 100%)",
    borderRadius: theme.radius.lg,
    padding: theme.spacing.lg,
    background: theme.colors.surface,
    border: `1px solid ${theme.colors.border}`,
  },
  back: { textDecoration: "none", color: "#444" },

  headerRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    marginTop: 10,
  },
  title: { margin: 0, fontSize: 28, color: theme.colors.text },

  helper: { marginTop: 12, marginBottom: 0, opacity: 0.85, color: "#333" },

  section: {
    marginTop: 18,
    paddingTop: 12,
    borderTop: "1px solid rgba(0,0,0,0.08)",
  },
  sectionTitle: {
    margin: "0 0 10px 0",
    fontSize: 18,
    color: theme.colors.text,
  },

  muted: { margin: 0, color: theme.colors.muted },
  error: { marginTop: 12, color: theme.colors.danger },

  codePill: {
    display: "flex",
    alignItems: "baseline",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 14,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: theme.colors.surface2,
  },
  codeLabel: {
    fontSize: 12,
    color: theme.colors.muted,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  codeValue: {
    fontFamily: theme.font.mono,
    fontSize: 18,
    color: theme.colors.text,
    letterSpacing: 2,
  },

  button: {
    padding: "10px 14px",
    borderRadius: 12,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: theme.colors.primary,
    color: theme.colors.primaryText,
    fontWeight: 700,
  },

  textarea: {
    marginTop: 12,
    width: "100%",
    padding: 12,
    borderRadius: 12,
    border: `1px solid ${theme.colors.borderStrong}`,
    background: "#fff",
    color: theme.colors.text,
    resize: "vertical",
    fontSize: 14,
    lineHeight: 1.4,
  },

  playerGrid: {
    marginTop: 12,
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 12,
  },
  playerCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: 12,
    borderRadius: 14,
    border: `1px solid ${theme.colors.border}`,
    background: "#fff",
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: 12,
    display: "grid",
    placeItems: "center",
    background: theme.colors.primary,
    color: theme.colors.primaryText,
    fontWeight: 700,
  },
  playerName: { fontSize: 16, color: theme.colors.text },
};
